baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Beellz blog"
  subtitle    = "Work on results"

  cover       = "uploads/back-1.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "belal20795"
  fbName = "belalthecoolboy"
  githubName = "beellz"

  logo = "uploads/BZ.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Beellz"
  authorAvatar = "uploads/logo-avatar.jpg"
  authorLocation = "MUMBAI , India"
  authorWebsite = "https://github.com/beellz"
  authorDescription = "Work on results"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "PROJECTS"
  url = "/tags/projects/"
  weight = 100

[[menu.main]]
  name = "MY LIFE"
  url = "/tags/my-life"
  weight = 99

[[menu.main]]
  name = "YOUTUBE"
  url = "https://www.youtube.com/channel/UC7xs-jRRKH_1piJv2HiC1bA"
  weight = 95